### ISSUE TITLE
Timeout is exceeded when uploading an asset

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-portal#36]
**Conditions:** 
* Chrome Version 92.0.4515.131 (Official Build) (64-bit)
* without Illinois VPN
* and with Illinois VPN

**Expected behavior:** 
Successful upload, or error feedback in UI

**Actual behavior:** 
"Uploading" button spins forever. The console shows `Uncaught (in promise) Error: timeout of 2500ms exceeded`.

![2021-08-06-upload-asset-timeout-on-vpn](https://user-images.githubusercontent.com/8165314/128735704-b4d17999-6649-424c-9381-888e921c3e5d.png)

(8/4)

**Comment by parseccentric** [comment]
This looks related to me:
```
(node:1) UnhandledPromiseRejectionWarning: Error: Unable to create a POST object policy without a bucket, region, and credentials
    at features.constructor.preparePostFields (/komodo/portal/backend/node_modules/aws-sdk/lib/services/s3.js:989:13)
    at finalizePost (/komodo/portal/backend/node_modules/aws-sdk/lib/services/s3.js:952:22)
    at /komodo/portal/backend/node_modules/aws-sdk/lib/services/s3.js:969:24
    at finish (/komodo/portal/backend/node_modules/aws-sdk/lib/config.js:357:7)
    at /komodo/portal/backend/node_modules/aws-sdk/lib/config.js:375:9
    at Credentials.get (/komodo/portal/backend/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/komodo/portal/backend/node_modules/aws-sdk/lib/config.js:369:24)
    at Config.getCredentials (/komodo/portal/backend/node_modules/aws-sdk/lib/config.js:389:9)
    at features.constructor.createPresignedPost (/komodo/portal/backend/node_modules/aws-sdk/lib/services/s3.js:964:14)
    at presignAssetPost (/komodo/portal/backend/service/asset.js:18:6)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

**Comment by wallacerob** [comment]
yeah we were using a hardcoded value for the bucket previously, which is now moved into the config file. Because this file is ignored (ie. only the template was updated), we don't have a bucket name in the existing config.js

**Comment by wallacerob** [comment]
i can fix if you like

**Comment by parseccentric** [comment]
Ok, that would be great! Thanks

**Comment by wallacerob** [comment]
ok works now

**Comment by parseccentric** [comment]
Nice! Working on my end too. Thank you!
