### ISSUE TITLE
Packets out of order, Unexpected token, Bind parameters must not contain undefined, other errors

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-portal#43]
On the dev server, using docker-compose up --build

v1.2.1

```
komodo-portal-frontend | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
komodo-portal-frontend | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
komodo-portal-frontend | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
komodo-portal-frontend | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
komodo-portal-frontend | 10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
komodo-portal-frontend | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-backend | Warning: got packets out of order. Expected 12 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 6 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 8 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 6 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 11 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 18 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 14 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 14 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 14 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 9 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 16 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 24 but received 0
komodo-portal-backend | (node:1) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token o in JSON at position 1
komodo-portal-backend |     at JSON.parse (<anonymous>)
komodo-portal-backend |     at getAllCsvExport (/komodo/portal/backend/service/data.js:59:34)
komodo-portal-backend |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
komodo-portal-backend |     at async /komodo/portal/backend/controller/data.js:48:17
komodo-portal-backend | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
komodo-portal-backend | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
komodo-portal-backend | /komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
komodo-portal-backend |         throw e;
komodo-portal-backend |         ^
komodo-portal-backend |
komodo-portal-backend | TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
komodo-portal-backend |     at Array.forEach (<anonymous>)
komodo-portal-backend |     at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:45:37
komodo-portal-backend |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-backend | /komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
komodo-portal-backend |         throw e;
komodo-portal-backend |         ^
komodo-portal-backend |
komodo-portal-backend | TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
komodo-portal-backend |     at Array.forEach (<anonymous>)
komodo-portal-backend |     at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:64:16
komodo-portal-backend |     at PoolConnection.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:777:13)
komodo-portal-backend |     at Object.onceWrapper (events.js:422:26)
komodo-portal-backend |     at PoolConnection.emit (events.js:315:20)
komodo-portal-backend |     at PoolConnection.EventEmitter.emit (domain.js:483:12)
komodo-portal-backend |     at ClientHandshake.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:121:14)
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-backend | Warning: got packets out of order. Expected 58 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 23 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 11 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 18 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 237 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 11 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 18 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 237 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 11 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 18 but received 0
komodo-portal-backend | Warning: got packets out of order. Expected 226 but received 0
komodo-portal-backend | /komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
komodo-portal-backend |         throw e;
komodo-portal-backend |         ^
komodo-portal-backend |
komodo-portal-backend | TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
komodo-portal-backend |     at Array.forEach (<anonymous>)
komodo-portal-backend |     at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:45:37
komodo-portal-backend |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-backend | /komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
komodo-portal-backend |         throw e;
komodo-portal-backend |         ^
komodo-portal-backend |
komodo-portal-backend | TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
komodo-portal-backend |     at Array.forEach (<anonymous>)
komodo-portal-backend |     at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:64:16
komodo-portal-backend |     at PoolConnection.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:777:13)
komodo-portal-backend |     at Object.onceWrapper (events.js:422:26)
komodo-portal-backend |     at PoolConnection.emit (events.js:315:20)
komodo-portal-backend |     at PoolConnection.EventEmitter.emit (domain.js:483:12)
komodo-portal-backend |     at ClientHandshake.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:121:14)
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-backend | /komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
komodo-portal-backend |         throw e;
komodo-portal-backend |         ^
komodo-portal-backend |
komodo-portal-backend | TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
komodo-portal-backend |     at Array.forEach (<anonymous>)
komodo-portal-backend |     at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:45:37
komodo-portal-backend |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-backend | /komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
komodo-portal-backend |         throw e;
komodo-portal-backend |         ^
komodo-portal-backend |
komodo-portal-backend | TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
komodo-portal-backend |     at Array.forEach (<anonymous>)
komodo-portal-backend |     at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:64:16
komodo-portal-backend |     at PoolConnection.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:777:13)
komodo-portal-backend |     at Object.onceWrapper (events.js:422:26)
komodo-portal-backend |     at PoolConnection.emit (events.js:315:20)
komodo-portal-backend |     at PoolConnection.EventEmitter.emit (domain.js:483:12)
komodo-portal-backend |     at ClientHandshake.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:121:14)
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-backend | /komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
komodo-portal-backend |         throw e;
komodo-portal-backend |         ^
komodo-portal-backend |
komodo-portal-backend | TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
komodo-portal-backend |     at Array.forEach (<anonymous>)
komodo-portal-backend |     at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:45:37
komodo-portal-backend |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-backend | Warning: got packets out of order. Expected 12 but received 0
komodo-portal-backend | /komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
komodo-portal-backend |         throw e;
komodo-portal-backend |         ^
komodo-portal-backend |
komodo-portal-backend | TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
komodo-portal-backend |     at Array.forEach (<anonymous>)
komodo-portal-backend |     at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
komodo-portal-backend |     at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:45:37
komodo-portal-backend |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
komodo-portal-backend | Komodo portal backend listening on port 4040!
komodo-portal-frontend | /docker-entrypoint.sh: Configuration complete; ready for start up
```

**Comment by parseccentric** [comment]
Since it might be related, I will just tack it onto here:

If you try to make a data request on a capture, this happens: 

```
Uncaught (in promise) Error: timeout of 2500ms exceeded
    at e.exports (createError.js:16)
    at XMLHttpRequest.h.ontimeout (xhr.js:89)
```
