### ISSUE TITLE
Login Fails

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-portal#48]
```
Access to XMLHttpRequest at 'https://api.komodo-dev.library.illinois.edu/users/login' from origin 'https://komodo-dev.library.illinois.edu' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xhr.js:172 POST https://api.komodo-dev.library.illinois.edu/users/login net::ERR_FAILED
(anonymous) @ xhr.js:172
e.exports @ xhr.js:11
e.exports @ dispatchRequest.js:59
Promise.then (async)
l.request @ Axios.js:53
l.<computed> @ Axios.js:78
(anonymous) @ bind.js:9
W @ auth.js:5
login @ Login.vue:104
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
nt @ vue.runtime.esm.js:1854
An.e.$emit @ vue.runtime.esm.js:3882
click @ vuetify.js:2475
nt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Zr.a._wrapper @ vue.runtime.esm.js:6911
Login.vue:127 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at Login.vue:127
```

**Comment by parseccentric** [comment]
Here's some content from the back end logs that are probably relevant.

```
Komodo portal backend listening on port 4040!
(node:1) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at getAllCsvExport (/komodo/portal/backend/service/data.js:60:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /komodo/portal/backend/controller/data.js:48:17
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at getAllCsvExport (/komodo/portal/backend/service/data.js:60:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /komodo/portal/backend/controller/data.js:48:17
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at getAllCsvExport (/komodo/portal/backend/service/data.js:60:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /komodo/portal/backend/controller/data.js:48:17
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1) UnhandledPromiseRejectionWarning: Error: Table 'komodo.can_access_capture_files' doesn't exist
    at PromisePool.execute (/komodo/portal/backend/node_modules/mysql2/promise.js:359:22)
    at getCourseAccess (/komodo/portal/backend/service/course.js:147:36)
    at /komodo/portal/backend/controller/course.js:85:27
    at Layer.handle [as handle_request] (/komodo/portal/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/komodo/portal/backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/komodo/portal/backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/komodo/portal/backend/node_modules/express/lib/router/layer.js:95:5)
    at /komodo/portal/backend/node_modules/express/lib/router/index.js:281:22
    at param (/komodo/portal/backend/node_modules/express/lib/router/index.js:354:14)
    at param (/komodo/portal/backend/node_modules/express/lib/router/index.js:365:14)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
/komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
        throw e;
        ^

TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:45:37
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Komodo portal backend listening on port 4040!
/komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
        throw e;
        ^

TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:64:16
    at PoolConnection.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:777:13)
    at Object.onceWrapper (events.js:422:26)
    at PoolConnection.emit (events.js:315:20)
    at PoolConnection.EventEmitter.emit (domain.js:483:12)
    at ClientHandshake.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:121:14)
Komodo portal backend listening on port 4040!
/komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
        throw e;
        ^

TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:45:37
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Komodo portal backend listening on port 4040!
/komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
        throw e;
        ^

TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:64:16
    at PoolConnection.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:777:13)
    at Object.onceWrapper (events.js:422:26)
    at PoolConnection.emit (events.js:315:20)
    at PoolConnection.EventEmitter.emit (domain.js:483:12)
    at ClientHandshake.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:121:14)
Komodo portal backend listening on port 4040!
/komodo/portal/backend/node_modules/mysql2/lib/pool.js:177
        throw e;
        ^

TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at /komodo/portal/backend/node_modules/mysql2/lib/connection.js:628:17
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:620:22)
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:172:14
    at /komodo/portal/backend/node_modules/mysql2/lib/pool.js:64:16
    at PoolConnection.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:777:13)
    at Object.onceWrapper (events.js:422:26)
    at PoolConnection.emit (events.js:315:20)
    at PoolConnection.EventEmitter.emit (domain.js:483:12)
    at ClientHandshake.<anonymous> (/komodo/portal/backend/node_modules/mysql2/lib/connection.js:121:14)
```

**Comment by parseccentric** [comment]
Relevant to v1.3.0-alpha
